<script lang="ts">
	import { page } from '$app/state';
	import type { Locale } from '$lib/i18n';
	import LegalShell from '$lib/ui/LegalShell.svelte';
	import ManagedDocument from '$lib/ui/ManagedDocument.svelte';

	const locale: Locale = $derived((page.data.locale as Locale | undefined) ?? 'tr');
	const titles: Record<Locale, string> = {
		en: 'Professional Disclaimer',
		tr: 'Profesyonel Sorumluluk Reddi',
		de: 'Beruflicher Haftungsausschluss'
	};
	const title = $derived(String(page.data.publicCopy?.disclaimer?.title ?? titles[locale]));
	const managedBody = $derived(String(page.data.publicCopy?.disclaimer?.body ?? '').trim());
</script>

<LegalShell {title}>
	{#if managedBody}<ManagedDocument text={managedBody} />{:else}
		{#if locale === 'en'}
			<p class="sk-callout">
				<strong>Important:</strong> This describes the nature of website content generated by saaskaya.
				Professional legal review is recommended before publication.
			</p>
			<h2>1. General disclaimer</h2>
			<p>
				AI-generated website content is a <strong>draft</strong>, not professional advice. It is
				intended for general information and must be reviewed for each professional's circumstances.
				saaskaya does not guarantee accuracy, completeness, legal compliance, or business results.
				You are responsible for reviewing content before publishing.
			</p>
			<h2>2. Regulated professions</h2>
			<p>
				For psychologists, lawyers, dentists, and other regulated professionals, content must not
				promise diagnoses, treatments, legal outcomes, guaranteed results, or use misleading
				credentials or comparisons. Professional scope, applicable advertising rules, and local
				regulatory requirements remain the site owner's responsibility.
			</p>
			<h2>3. AI content responsibility</h2>
			<p>
				AI output must always be reviewed and approved before publication. The model may not know
				every professional, ethical, or legal rule, and saaskaya is not responsible for the
				consequences of published content.
			</p>
			<h2>4. Contact forms and third parties</h2>
			<p>
				A contact form does not create a professional-client relationship and is not an encrypted
				communication channel. Booking, payment, and other third-party integrations are provided by
				their respective operators; saaskaya does not guarantee their uninterrupted operation.
			</p>
			<h2>5. Translation and changes</h2>
			<p>
				Multilingual content may contain terminology or legal nuances requiring professional review.
				This disclaimer may be updated as relevant rules change. Questions and content-review
				requests: <a href="mailto:destek@saaskaya.com">destek@saaskaya.com</a>.
			</p>
		{:else if locale === 'de'}
			<p class="sk-callout">
				<strong>Wichtig:</strong> Dieser Text beschreibt den Charakter der von saaskaya erzeugten Website-Inhalte.
				Vor der Veröffentlichung wird eine professionelle rechtliche Prüfung empfohlen.
			</p>
			<h2>1. Allgemeiner Haftungsausschluss</h2>
			<p>
				KI-generierte Website-Inhalte sind ein <strong>Entwurf</strong>, keine professionelle
				Beratung. Sie dienen der allgemeinen Information und müssen für die jeweilige berufliche
				Situation geprüft werden. saaskaya übernimmt keine Gewähr für Richtigkeit, Vollständigkeit,
				Rechtskonformität oder Geschäftsergebnisse. Du bist vor der Veröffentlichung für die Prüfung
				verantwortlich.
			</p>
			<h2>2. Regulierte Berufe</h2>
			<p>
				Für Psycholog:innen, Anwält:innen, Zahnärzt:innen und andere regulierte Berufe dürfen
				Inhalte keine Diagnosen, Behandlungen, Rechtsausgänge oder garantierte Ergebnisse
				versprechen und keine irreführenden Qualifikationen oder Vergleiche enthalten. Beruflicher
				Umfang, Werberegeln und lokale Vorgaben liegen beim Website-Inhaber.
			</p>
			<h2>3. Verantwortung für KI-Inhalte</h2>
			<p>
				KI-Ausgaben müssen vor der Veröffentlichung stets geprüft und freigegeben werden. Das Modell
				kennt möglicherweise nicht jede Berufs-, Ethik- oder Rechtsregel; saaskaya haftet nicht für
				Folgen veröffentlichter Inhalte.
			</p>
			<h2>4. Kontaktformulare und Dritte</h2>
			<p>
				Ein Kontaktformular begründet keine professionelle Mandats- oder Behandlungsbeziehung und
				ist kein verschlüsselter Kommunikationskanal. Buchungs-, Zahlungs- und andere
				Drittintegrationen werden von ihren jeweiligen Betreibern bereitgestellt; saaskaya
				garantiert keinen unterbrechungsfreien Betrieb.
			</p>
			<h2>5. Übersetzung und Änderungen</h2>
			<p>
				Mehrsprachige Inhalte können Terminologie oder rechtliche Nuancen enthalten, die
				professionell geprüft werden müssen. Dieser Haftungsausschluss kann bei Regeländerungen
				aktualisiert werden. Fragen und Prüfungsanfragen: <a href="mailto:destek@saaskaya.com"
					>destek@saaskaya.com</a
				>.
			</p>
		{:else}
			<p class="sk-callout">
				<strong>Önemli:</strong> Bu metin, saaskaya tarafından üretilen site içeriğinin niteliğini tanımlar.
				Yayın öncesi operatör hukuki gözden geçirmesi önerilir.
			</p>

			<h2>1. Genel Sorumluluk Reddi</h2>
			<p>
				saaskaya tarafından AI ile üretilen site içeriği bir <strong>taslaktır</strong>, profesyonel
				tavsiye değildir. İçerik, genel bilgi verme amacıyla hazırlanır ve her profesyonelin kendi
				mesleki durumuna göre gözden geçirilmesini gerektirir.
			</p>
			<p>
				saaskaya, üretilen içeriğin doğruluğu, tamlığı, yasal uyumluluğu veya iş sonucu garantisi
				vermez. Site içeriğini yayınlamadan önce gözden geçirmek <strong>sizin</strong>
				sorumluluğunuzdadır.
			</p>

			<h2>2. Psikologlar İçin Özel Reddi (Launch Nişi)</h2>
			<p>Psikolog müşterilerimizin sitelerinde aşağıdaki sınırlar geçerlidir:</p>
			<ul>
				<li>
					<strong>Tıbbi teşhis/tedavi iddiası yok:</strong> Site içeriği teşhis koyma, tedavi etme veya
					tıbbi tavsiye verme amacı taşımaz. Psikolojik değerlendirme ve tedavi, yalnızca yüz yüze veya
					uygun uzaktan ortamda, profesyonel tarafından yapılır.
				</li>
				<li>
					<strong>Sonuç garantisi yok:</strong> "Garantili iyileşme", "%100 başarı", "kesin çözüm" gibi
					ifadeler yasaktır. Terapi sonuçları bireye göre değişir.
				</li>
				<li>
					<strong>Meslektaş küçümsemesi yok:</strong> Diğer psikologları/psikiyatristleri küçümseyici
					veya karşılaştırmalı iddialar yasaktır (Sağlık Hizmetleri Reklam Yönetmeliği).
				</li>
				<li>
					<strong>Yetki sınırları:</strong> Klinik psikolog ile uzman psikolog ayrımı doğru yapılmalı;
					reçete yetkisi olmadığı belirtilmelidir (ilaç tedavisi psikiyatriste yönlendirme).
				</li>
				<li>
					<strong>Kriz yönlendirmesi:</strong> Akut kriz/ intihar riski durumunda 112 veya acil psikiyatri
					no'suna yönlendirme önerilir.
				</li>
			</ul>

			<h2>3. Avukatlar İçin Özel Reddi</h2>
			<ul>
				<li>
					<strong>Hukuki tavsiye değil:</strong> Site içeriği hukuki tavsiye yerine geçmez; danışmanlık
					ilişkisi ancak ayrı bir sözleşmeyle kurulur.
				</li>
				<li>
					<strong>Başarı garantisi yok:</strong> "Kazanılır dava", "%100 başarı" gibi ifadeler yasaktır
					(TBB reklam yönetmeliği).
				</li>
				<li>
					<strong>Uzmanlık alanı:</strong> Hukuk alanı (aile, ceza, ticari vb.) doğru belirtilmeli; yanıltıcı
					uzmanlık iddiası yasaktır.
				</li>
			</ul>

			<h2>4. Diş Hekimleri İçin Özel Reddi</h2>
			<ul>
				<li>
					<strong>Tıbbi sonuç iddiası yok:</strong> "Ağrısız implant", "garantili sonuç", "tek seansda
					biter" gibi ifadeler yasaktır (Sağlık Bakanlığı reklam yönetmeliği).
				</li>
				<li>
					<strong>Öncesi-sonrası görsel yok:</strong> Hasta görseleri açık onay olmadan ve yönetmelik
					izni olmadan yayınlanamaz.
				</li>
				<li>
					<strong>Karşılaştırmalı reklam yok:</strong> Diğer kliniklerle fiyat/sonuç karşılaştırması yasaktır.
				</li>
			</ul>

			<h2>5. AI Üretimi ve İçerik Sorumluluğu</h2>
			<p>
				saaskaya'nın AI'ı, mesleki etik ve reklam yönetmeliklerine uygun içerik üretmeye çalışır,
				ancak:
			</p>
			<ul>
				<li>AI çıktısı her zaman taslaktır; yayınlamadan önce siz onaylarsınız</li>
				<li>AI, mesleki etik kurallarının tamamını bilemeyebilir — gözden geçirme şart</li>
				<li>İçeriğin yasal uyumluluğu tamamen site sahibine aittir</li>
				<li>saaskaya, yayınlanan içeriğin sonuçlarından sorumlu değildir</li>
			</ul>

			<h2>6. İletişim Formu ve Danışan İlişkisi</h2>
			<p>
				Sitenizdeki iletişim formu, potansiyel danışan/danışan ile ilk teması kurar. Bu, bir
				profesyonel hizmet ilişkisi başlatmaz — ayrı bir değerlendirme/seans sözleşmesi gerekir.
				İletişim formundan gelen mesajlar gizli kabul edilmemelidir (şifreli iletişim kanalı
				değildir).
			</p>

			<h2>7. Çeviri ve Çok Dilli İçerik</h2>
			<p>
				TR/EN/DE çeviriler, AI tarafından yapılır. Çevirilerde mesleki terminoloji veya yasal
				nüanslar tam korunmayabilir. Yabancı danışanlara yönelik içerik yayınlamadan önce ilgili
				dilde profesyonel gözden geçirme önerilir.
			</p>

			<h2>8. Üçüncü Taraf Hizmetleri</h2>
			<p>
				Sitenizdeki randevu/booking, ödeme veya harici entegrasyonlar (varsa) üçüncü taraflar
				tarafından sağlanır. saaskaya, bu hizmetlerin kesintisiz veya hatasız çalışmasını garanti
				etmez.
			</p>

			<h2>9. Değişiklikler</h2>
			<p>
				Bu sorumluluk reddi, ilgili yönetmelikler değiştikçe güncellenebilir. Önemli değişiklikler
				e-posta ile bildirilir.
			</p>

			<h2>10. İletişim</h2>
			<p>
				Soru ve içerik gözden geçirme talepleri:
				<a href="mailto:destek@saaskaya.com">destek@saaskaya.com</a>
			</p>
		{/if}
	{/if}
</LegalShell>
